import React from 'react';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../../styles/Home.module.css';
import Navbar from '../Navbar';
import Footer from './Footer';
// eslint-disable-next-line react/prop-types
function Layout({ children }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>NextJs starter</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="/Icon/favicon.ico" />
        <link
          rel="mask-icon"
          href="/Icon/safari-pinned-tab.svg"
          color="#5bbad5"
        />
      </Head>
      <main className={styles.main}>
        <div
          className=" justify-center m-2 flex bg-sky-300  center"
          style={{ width: 740 }}
        >
          <Image
            className="object-cover h-48 w-96"
            alt="banner-img"
            src="/banner.jpg"
            objectFit="cover"
            width={2000}
            height={1000}
          />
        </div>
        <h1 className="flex m-1 p-4 text-4xl">Welcome to Next.js Starter!</h1>
        <p className=" flex text-2xl p-4 m-2">
          Get started by editing{' '}
          <code className="bg-slate-100 px-1 mx-1 rounded-md">
            pages/index.tsx
          </code>
        </p>
        <Navbar />
        {children}
      </main>
      <Footer />
    </div>
  );
}

export default Layout;
